---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "minecraft-bedrock-server.fullname" . }}-configmap
  labels:
    {{- include "minecraft-bedrock-server.labels" . | nindent 4 }}
{{- with .Values.configMap }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}