apiVersion: v1
kind: Service
metadata:
  name: {{ include "minecraft-bedrock-server.fullname" . }}-sidecar
  labels:
    {{- include "minecraft-bedrock-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.sidecar.service.type }}
  ports:
    - port: {{ .Values.sidecar.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "minecraft-bedrock-server.selectorLabels" . | nindent 4 }}
